- .eslintrc.json
- __tests__/redux/reducers.test.js
- client/src/index.jsx
- package.json
> working on redux reducer test

- client/src/actions/productActions.js
- client/src/actions/questionsActions.js
- client/src/components/App.jsx
- client/src/lib/API_URL.js
- client/src/reducers/questionsReducer.js
- client/src/store.js
@Sokushinbutsu @cali3192 @thunderbolt520 
Please review,
I rebased off of Cali's last merge with the review reducer so everything should be good.
> Question reducer

- __tests__/__snapshots__/App.test.js.snap
- client/src/actions/relatedActions.js
- client/src/actions/reviewActions.js
- client/src/components/App.jsx
- client/src/reducers/relatedReducer.js
- client/src/store.js
This PR adds the getRelatedIDs action and related reducer. I also renamed the actions that are used in mapStateToProps.
> Integrate related

- __tests__/__snapshots__/App.test.js.snap
- client/src/actions/reviewActions.js
- client/src/components/App.jsx
- client/src/components/Reviews/RevParentComponent.jsx
created a parent container so that I can do work on that rather than adding the different components in App.jsx. This will hopefully minimize merge conflicts.
> reviews parent container

- index.js
> serve client code at any endpoint

- client/src/actions/reviewsActions.js
- client/src/components/App.jsx
- mocks/fetchProductMock.js
PR - fixed the payload for product
> fixed mock data for product

- __tests__/__snapshots__/App.test.js.snap
- client/src/components/App.jsx
- client/src/components/Reviews/RevParentComponent.jsx
PR for creating my basic grid framework - functionality will follow
> Reviews grid

- __tests__/__snapshots__/App.test.js.snap
- client/src/components/Reviews/AddReviewModal.jsx
- client/src/components/Reviews/ComfortGraph.jsx
- client/src/components/Reviews/MoreReviews.jsx
- client/src/components/Reviews/Recommended.jsx
- client/src/components/Reviews/RevParentComponent.jsx
- package-lock.json
- package.json
PR - added some icons and components - no functionality yet
> More reviews button

- __tests__/__snapshots__/App.test.js.snap
- client/src/components/App.jsx
- client/src/components/Reviews/ReviewsAPICalls.jsx
> Reviews api calls

- client/src/actions/reviewsActions.js
- client/src/reducers/reviewsReducer.js
PR - form with add review modal completed
> Review redux post

- client/src/actions/reviewsActions.js
- client/src/components/Reviews/ReviewsAPICalls.jsx
- client/src/reducers/reviewsReducer.js
- client/src/store.js
PR - Added meta information for reviews
> Reviews api meta

- client/src/components/App.jsx
- client/src/components/Reviews/ReviewsWrapper.jsx
> modified naming

- client/src/components/App.jsx
- client/src/components/Reviews/RevParentComponent.jsx
- client/src/components/Reviews/ReviewEntry.jsx
- client/src/components/Reviews/ReviewList.jsx
- client/src/components/Reviews/ReviewsWrapper.jsx
PR - generating data based on route
> Reviews list data

- client/src/components/App.jsx
- client/src/components/Reviews/RevParentComponent.jsx
- client/src/components/Reviews/ReviewsWrapper.jsx
- client/src/components/Reviews/StarGraphsList.jsx
PR - working on trying to normalize graph
> Meta stars

- client/src/components/Reviews/AddReviewModal.jsx
- client/src/components/Reviews/AverageRev.jsx
- client/src/components/Reviews/MoreReviews.jsx
- client/src/components/Reviews/Recommended.jsx
- client/src/components/Reviews/Relevance.jsx
- client/src/components/Reviews/RevParentComponent.jsx
- client/src/components/Reviews/ReviewEntry.jsx
- client/src/components/Reviews/ReviewList.jsx
- client/src/components/Reviews/StarGraphsList.jsx
- package-lock.json
- package.json
> Stying reviews

- client/src/components/Reviews/ReviewEntry.jsx
PR - updated some basic styles
> Reviews stye reviews entry

- client/src/components/App.jsx
- client/src/components/Questions/AnswerModal.jsx
- client/src/components/Reviews/AddReviewModal.jsx
- client/src/components/Reviews/ReviewForm.jsx
- client/src/components/Reviews/ReviewList.jsx
> Reviews modal scroll

- client/src/components/App.jsx
- client/src/components/Reviews/AverageRev.jsx
- client/src/components/Reviews/Recommended.jsx
- client/src/components/Reviews/ReviewEntry.jsx
- client/src/components/Reviews/ReviewForm.jsx
- package-lock.json
- package.json
> Reviews stars

- client/src/components/Reviews/Recommended.jsx
- client/src/components/Reviews/StarGraphsList.jsx
- client/src/lib/normalize.js
PR - dynamically rendering star graph
> Reviews star graph

- client/src/actions/reviewsActions.js
- client/src/components/Reviews/RevParentComponent.jsx
- client/src/components/Reviews/ReviewCounter.jsx
> still need to test

- client/src/actions/reviewsActions.js
- client/src/components/Reviews/Report.jsx
- client/src/components/Reviews/RevParentComponent.jsx
- client/src/components/Reviews/ReviewCounter.jsx
- client/src/components/Reviews/ReviewEntry.jsx
- client/src/components/Reviews/ReviewList.jsx
PR - fixed report and updated the number of reviews counter
> Reviews report

- client/src/components/Related/ProductCard.jsx
> Added default image

- client/src/components/Reviews/Form/Charcteristics.jsx
- client/src/components/Reviews/Form/Comfort.jsx
- client/src/components/Reviews/Form/Fit.jsx
- client/src/components/Reviews/Form/Form.jsx
- client/src/components/Reviews/Form/Length.jsx
- client/src/components/Reviews/Form/Quality.jsx
- client/src/components/Reviews/Form/Recommend.jsx
- client/src/components/Reviews/Form/ReviewBody.jsx
- client/src/components/Reviews/Form/Size.jsx
- client/src/components/Reviews/Form/Username.jsx
- client/src/components/Reviews/Form/Width.jsx
- client/src/components/Reviews/RevParentComponent.jsx
PR - added characteristics in form
> Reviews form fix
